server:
  port: 8080
  servlet:
    context-path: "/api"

spring:
  application:
    name: greenimpact

  datasource:
    url: jdbc:postgresql://localhost/green-impact
    username: ${LOGIN_BD:greenimpact}
    password: ${PASS_BD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect


  flyway:
    locations: classpath:/db/migrations
    enabled: true
    baseline-on-migrate: true

