server:
  port: ${PORT}
  servlet:
    context-path: "/api"

logging:
  level:
    org:
      hibernate.orm.connections.pooling: warn

jwt:
  secret_key: "${JWT_SECRET}"
  access_token_expiration: "${JWT_LIFETIME_ACCESS}" # 10 hours

spring:
  config:
    import: file:.env[.properties]
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: greenimpact

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        boot:
          allow_jdbc_metadata_access: false


  flyway:
    locations: classpath:/db/migrations
    enabled: true
    baseline-on-migrate: true

open-cage:
  api-key: "${OPEN_CAGE_API}"

s3:
  access-key: "${S3_ACCESS_KEY}"
  secret-key: "${S3_SECRET_KEY}"
  bucket-name: "${S3_BUCKET_NAME}"

